/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WallSlugRouteImport } from './routes/wall.$slug'
import { Route as StaffSlugRouteImport } from './routes/staff.$slug'
import { Route as GCodeRouteImport } from './routes/g.$code'
import { Route as ESlugRouteImport } from './routes/e.$slug'
import { Route as ESlugGalleryRouteImport } from './routes/e.$slug.gallery'
import { Route as ApiPublicProcessPhotoRouteImport } from './routes/api/public/process-photo'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WallSlugRoute = WallSlugRouteImport.update({
  id: '/wall/$slug',
  path: '/wall/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffSlugRoute = StaffSlugRouteImport.update({
  id: '/staff/$slug',
  path: '/staff/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GCodeRoute = GCodeRouteImport.update({
  id: '/g/$code',
  path: '/g/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ESlugRoute = ESlugRouteImport.update({
  id: '/e/$slug',
  path: '/e/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ESlugGalleryRoute = ESlugGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => ESlugRoute,
} as any)
const ApiPublicProcessPhotoRoute = ApiPublicProcessPhotoRouteImport.update({
  id: '/api/public/process-photo',
  path: '/api/public/process-photo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/e/$slug': typeof ESlugRouteWithChildren
  '/g/$code': typeof GCodeRoute
  '/staff/$slug': typeof StaffSlugRoute
  '/wall/$slug': typeof WallSlugRoute
  '/api/public/process-photo': typeof ApiPublicProcessPhotoRoute
  '/e/$slug/gallery': typeof ESlugGalleryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/e/$slug': typeof ESlugRouteWithChildren
  '/g/$code': typeof GCodeRoute
  '/staff/$slug': typeof StaffSlugRoute
  '/wall/$slug': typeof WallSlugRoute
  '/api/public/process-photo': typeof ApiPublicProcessPhotoRoute
  '/e/$slug/gallery': typeof ESlugGalleryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/e/$slug': typeof ESlugRouteWithChildren
  '/g/$code': typeof GCodeRoute
  '/staff/$slug': typeof StaffSlugRoute
  '/wall/$slug': typeof WallSlugRoute
  '/api/public/process-photo': typeof ApiPublicProcessPhotoRoute
  '/e/$slug/gallery': typeof ESlugGalleryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/e/$slug'
    | '/g/$code'
    | '/staff/$slug'
    | '/wall/$slug'
    | '/api/public/process-photo'
    | '/e/$slug/gallery'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/e/$slug'
    | '/g/$code'
    | '/staff/$slug'
    | '/wall/$slug'
    | '/api/public/process-photo'
    | '/e/$slug/gallery'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/e/$slug'
    | '/g/$code'
    | '/staff/$slug'
    | '/wall/$slug'
    | '/api/public/process-photo'
    | '/e/$slug/gallery'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ESlugRoute: typeof ESlugRouteWithChildren
  GCodeRoute: typeof GCodeRoute
  StaffSlugRoute: typeof StaffSlugRoute
  WallSlugRoute: typeof WallSlugRoute
  ApiPublicProcessPhotoRoute: typeof ApiPublicProcessPhotoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wall/$slug': {
      id: '/wall/$slug'
      path: '/wall/$slug'
      fullPath: '/wall/$slug'
      preLoaderRoute: typeof WallSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/$slug': {
      id: '/staff/$slug'
      path: '/staff/$slug'
      fullPath: '/staff/$slug'
      preLoaderRoute: typeof StaffSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$code': {
      id: '/g/$code'
      path: '/g/$code'
      fullPath: '/g/$code'
      preLoaderRoute: typeof GCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$slug': {
      id: '/e/$slug'
      path: '/e/$slug'
      fullPath: '/e/$slug'
      preLoaderRoute: typeof ESlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$slug/gallery': {
      id: '/e/$slug/gallery'
      path: '/gallery'
      fullPath: '/e/$slug/gallery'
      preLoaderRoute: typeof ESlugGalleryRouteImport
      parentRoute: typeof ESlugRoute
    }
    '/api/public/process-photo': {
      id: '/api/public/process-photo'
      path: '/api/public/process-photo'
      fullPath: '/api/public/process-photo'
      preLoaderRoute: typeof ApiPublicProcessPhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ESlugRouteChildren {
  ESlugGalleryRoute: typeof ESlugGalleryRoute
}

const ESlugRouteChildren: ESlugRouteChildren = {
  ESlugGalleryRoute: ESlugGalleryRoute,
}

const ESlugRouteWithChildren = ESlugRoute._addFileChildren(ESlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ESlugRoute: ESlugRouteWithChildren,
  GCodeRoute: GCodeRoute,
  StaffSlugRoute: StaffSlugRoute,
  WallSlugRoute: WallSlugRoute,
  ApiPublicProcessPhotoRoute: ApiPublicProcessPhotoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
